### ISSUE TITLE
[PE-D][Tester C] Wrong Error Message for `pack` on integer overflow

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T14-2/tp#103]
![image.png](https://raw.githubusercontent.com/natashatanyt/ped/master/files/1c63cc1e-eade-4d6d-a2cd-2990f1d664eb.png)

When trying to add a huge number of quantity to be packed, it instead throws an invalid index error, instead of an invalid input quantity error

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: natashatanyt/ped#8

**Comment by linuspuah** [comment]
Number Format Exception refer to below website to understand
https://www.javatpoint.com/numberformatexception-in-java
in essence the `Integer.parseInt(quantityAndIndex[0])` in `createPackObj()` can only convert string to integer from a limited range, suggestion is to limit the maximum quantity of an item to be 100 

- need to check for similar error in integer unpack and packall (limit to tracking 100 items in a packing list)
