### ISSUE TITLE
[PE-D][Tester A] Functionality: List Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T14-2/tp#111]
![image.png](https://raw.githubusercontent.com/NivethaUdayakumar/ped/main/files/2a71d0ef-99be-4fdf-8a50-5f2b092f1460.png)

Based on UG usage instructions, should this "list 24" throw an error message like it does for "list2435"? 

![image.png](https://raw.githubusercontent.com/NivethaUdayakumar/ped/main/files/dd95dab1-5517-4699-9d4f-f6f96e1ecfc2.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: NivethaUdayakumar/ped#9

**Comment by linuspuah** [comment]
repeated issue
