### ISSUE TITLE
[PE-D][Tester B] Unable to add item

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T14-2/tp#116]
__Issue details:__

When attempting to add an item, the add operation fails.

__Steps to reproduce issue:__

1. Launch the application
2. Enter `add 123 /of add 123 /of test`

__Expected behaviour:__

```
New item added: [0/1] add 123 /of test
```

__Actual behaviour:__

```
add 123 /of add 123 /of test
/////////////////////////////////////////////////////////////
Error Invalid input format:
add : Adds quantity and name of item to the packing list.
        Example: add 3 /of toothbrush
        Meaning: add quantity of 3 toothbrushes to the packing list
/////////////////////////////////////////////////////////////
```

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jinxuan-owyong/ped#5

**Comment by linuspuah** [comment]
Error is because of the way `getAddVariables()` splits the input using /of,

**Comment by linuspuah** [comment]
similar error in editquantity command, source of error is `getEditQuantityVariables()`
