### ISSUE TITLE
incorrect error message for find command

### ISSUE THREAD

**Issue by linuspuah** [AY2223S2-CS2113-T14-2/tp#150]
![image](https://user-images.githubusercontent.com/88185250/230046386-9561c76f-8534-43e1-b527-4c0badd1e52b.png)

**Comment by tangphi** [comment]
<img width="735" alt="Screenshot 2023-04-05 at 10 24 25 pm" src="https://user-images.githubusercontent.com/50645666/230111149-7d96ec8f-803a-4c91-bf00-c325625bdd7d.png">
Bug seems to be fixed based on latest PR?
