### ISSUE TITLE
[PE-D][Tester C] Better formatting for UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T14-2/tp#97]
![image.png](https://raw.githubusercontent.com/natashatanyt/ped/master/files/85f51b24-5c39-48b8-91c3-e1e2c69701b3.png)

It would be better to format this into an actual table instead of bullet points + table

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: natashatanyt/ped#5

**Comment by shannentan** [comment]
Resolved in latest commit
